# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HNCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Endereço de Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Sobrenome')),
                ('birthdate', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('sex', models.CharField(blank=True, choices=[('', 'Escolha uma opção...'), ('m', 'Masculino'), ('f', 'Feminino')], max_length=20, verbose_name='Sexo')),
                ('occupation', models.IntegerField(blank=True, choices=[(None, 'Escolha uma ocupacao...'), (0, 'Estudo'), (1, 'Trabalho'), (2, 'Estudo e trabalho'), (3, 'Desocupado')], verbose_name='Ocupação')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Cidade')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='País')),
                ('profession', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profession', verbose_name='Profissão')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Region', verbose_name='Estado')),
                ('schooling', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Schooling', verbose_name='Escolaridade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
