# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hncuser',
            name='occupation',
            field=models.IntegerField(choices=[(None, 'Escolha uma ocupacao...'), (0, 'Estudo'), (1, 'Trabalho'), (2, 'Estudo e trabalho'), (3, 'Desocupado')], null=True, verbose_name='Ocupação'),
        ),
    ]
